### ISSUE TITLE
The excessive RU warning hides the entire data table in container items view

### ISSUE THREAD

**Issue by nickwb** [Azure/cosmos-explorer#1929]
Hi Cosmos Team,

@analogrelay - I am not 100% sure, but I believe this is a bug related to PR #1865 

The RU limit warning current hides the entire data view:
![image](https://github.com/user-attachments/assets/46fe2ead-1654-445e-9fb9-c33409407510)

**Comment by analogrelay** [comment]
Looks like this only happens when _two_ MessageBars are shown (in your example, the Network one and the RU Threshold one). Looking into the fix now.

**Comment by analogrelay** [comment]
I've opened https://github.com/Azure/cosmos-explorer/pull/1930 to fix this. Thanks for the report @nickwb! We'll work on getting this rolled out. Until then, dismissing the RU Threshold bar _should_ resolve your issue. Let me know if you run into a problem here you can't work around!

**Comment by nickwb** [comment]
Thanks for looking at this @analogrelay - Can confirm that it has been rolled out and looks correct now.
