### ISSUE TITLE
Need to add TimetoLivePropertyPath to TTL section in Data Explorer

### ISSUE THREAD

**Issue by timsander1** [Azure/cosmos-explorer#274]
Cosmos DB has a feature that allows you to set a custom path to be used in place of '_ts' when deciding whether to delete an item via TTL. As of now, setting and viewing the TimeToLivePropertyPath is possible through the SDK only. 

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.containerproperties.timetolivepropertypath?view=azure-dotnet#definition

The following example has been the cause of a few recent support tickets:

Contoso Dev Team has two developers: Alex and Bob.
	1. Alex sets TimeToLivePropertyPath to a customer property “/myTimestamp”
	2. Bob goes to use Cosmos DB later and can’t figure out why items aren’t being deleted based on TTL
	3. Bob doesn’t realize that Alex had set a TimeToLivePropertyPath. Bob is confused and sees this as unexplainable behavior

Being able to view and modify the TimeToLivePropertyPath in the Portal would help decrease confusion here.

**Comment by southpolesteve** [comment]
🙏 Thank you for filling this on GitHub. Is this value exposed via ARM? I am not seeing it in the swagger spec. We will need it exposed there first.

**Comment by timsander1** [comment]
I'll check on this

**Comment by timsander1** [comment]
Quick update on this, we decided we want to discourage customers from using this feature. It will be marked as deprecated in any SDK's where it is currently exposed. Based on this, we don't want to include this in the Portal. I'll go ahead and close this github issue.
