### ISSUE TITLE
Indexing "OFF" not respected for AAD logged in user with free tier account

### ISSUE THREAD

**Issue by southpolesteve** [Azure/cosmos-explorer#74]
From @languy: It appears that the indexing setting is (incorrectly) ignored for Graph and SQL API when the user is signed in with AAD. Under these conditions, the default settings are being used (automatic indexing), so choosing indexing OFF will produce the same result as indexing set to Automatic.

**Comment by victor-meng** [comment]
PR up: https://github.com/Azure/cosmos-explorer/pull/85
