### ISSUE TITLE
RBAC with Azure AD - Custom role not honoured?

### ISSUE THREAD

**Issue by thomasvdb** [Azure/cosmos-explorer#853]
I'm currently trying to setup RBAC with Azure AD by following "[Configure role-based access control with Azure Active Directory for your Azure Cosmos DB account](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac)".

I'm using the following Powershell script to create a read-only custom role and attach it to my Azure AD identity.

```
$resourceGroupName = "..."
$accountName = "..."

New-AzCosmosDBSqlRoleDefinition -AccountName $accountName `
    -ResourceGroupName $resourceGroupName `
    -Type CustomRole -RoleName MyReadOnlyRole `
    -DataAction @( `
        'Microsoft.DocumentDB/databaseAccounts/readMetadata',
        'Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/items/read', `
        'Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/executeQuery', `
        'Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/readChangeFeed') `
    -AssignableScope "/"

$readOnlyRoleDefinitionId = "[use ID from command above]"
$principalId = "[my principal ID]"
New-AzCosmosDBSqlRoleAssignment -AccountName $accountName `
    -ResourceGroupName $resourceGroupName `
    -RoleDefinitionId $readOnlyRoleDefinitionId `
    -Scope $accountName `
    -PrincipalId $principalId
```

As stated [in the documentation](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac#use-data-explorer) I should apply a query string parameter to use Azure AD RBAC on the Cosmos explorer; https://cosmos.azure.com/?feature.enableAadDataPlane=true.

However I can still update items in the collection of the configured Cosmos DB account.
Am I missing something?

**Comment by zfoster** [comment]
Hey @thomasvdb, I can help debug. In your network tab, does the request to update an item have an authorization header that starts with something like `type%3Daad%26ver%3D1.0%26sig`?

**Comment by zfoster** [comment]
I suspect you have access to the masterKey, which is like what's then being used to update items in the collection

**Comment by thomasvdb** [comment]
@zfoster Thanks for the quick response!

The authorization header starts with `type%3Dmaster%26ver%3D1.0%26sig...`.
What do you mean by "have access to the masterKey"? I can indeed access the keys of the Cosmos DB account.

Does this mean that the RBAC roles in the Azure portal override the Azure AD RBAC roles?

**Comment by zfoster** [comment]
That's right, in Cosmos Explorer we try to run `listKeys`, if the logged in tenant is missing permissions to fetch the keys we'll fallback to AAD RBAC

**Comment by ThomasWeiss** [comment]
@thomasvdb The data explorer behavior has been clarified in a recent doc update: https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac#use-data-explorer.
If the user has access to the primary key, that's what we use as it gives the largest scope anyway.

**Comment by thomasvdb** [comment]
@zfoster @ThomasWeiss Ok, that's clear. Appreciate the quick answers!
