### ISSUE TITLE
No load more button to fetch extra query results (with SQL Query)

### ISSUE THREAD

**Issue by bertcreemers** [Azure/cosmos-explorer#906]
Hi, 

I have noticed that a while ago there was a "Load more" button (see screenshot) to fetch extra pages with results after executing a sql query.
This button does not seems to exist anymore. Is there a reason for this?
Thans for the feedback.

Greetings, 

Bert Creemers

![MicrosoftTeams-image](https://user-images.githubusercontent.com/34474329/122900411-f36e4f00-d34c-11eb-9bfe-9171ee7855cb.png)

**Comment by southpolesteve** [comment]
@bertcreemers I see a "Load More" link on your screenshot right next to the number of results. Is that not working? I do think we could make it more visible.

**Comment by southpolesteve** [comment]
@bertcreemers I see the issue now. Fix is here https://github.com/Azure/cosmos-explorer/pull/907. Will have it deployed later today

**Comment by southpolesteve** [comment]
Fix has been deployed

**Comment by bertcreemers** [comment]
> Fix has been deployed

Thanks very much
