### ISSUE TITLE
Unable to delete Documents via the Azure Portal

### ISSUE THREAD

**Issue by Joncn89** [Azure/cosmos-explorer#960]
**Browser:**
- Google Chrome, Version 92.0.4515.107
- Microsoft Edge, Version 92.0.902.55
   

**Repro-Steps:**
- Open the "Data Explorer" in the Azure Portal
- Navigate to the "Items" pane of a Collection.
- Select a Item and press "Delete".
![image](https://user-images.githubusercontent.com/11848658/126986126-8d444c9f-7c27-4f90-b2df-bc6ff4fc1ac3.png)

   

**Outcome**
In the Console of the debugging-window of the browser the following error appears:
![image](https://user-images.githubusercontent.com/11848658/126985672-8a76463c-623e-47fd-b49b-19e5fbd2c68d.png)

> A different origin subframe tried to create a JavaScript dialog. This is no longer allowed and was blocked. See https://www.chromestatus.com/feature/5148698084376576 for more details.

As the dialog is not shown, I am unable to delete the item via the Azure Portal

**Comment by southpolesteve** [comment]
Thanks for the report. We'll work on a fix. In the meantime you can use https://cosmos.azure.com/ which does not suffer from the cross origin issue

**Comment by southpolesteve** [comment]
Fix has been deployed
